
local PLUGIN = PLUGIN;

function PLUGIN:ClockworkInitialized()
	cwStorage.containerList = {
		["models/props_wasteland/controlroom_storagecloset001a.mdl"] = {35, "Closet"},
		["models/props_wasteland/controlroom_storagecloset001b.mdl"] = {35, "Closet"},
		["models/props_wasteland/controlroom_filecabinet001a.mdl"] = {15, "File Cabinet"},
		["models/props_wasteland/controlroom_filecabinet002a.mdl"] = {15, "File Cabinet"},
		["models/props_c17/suitcase_passenger_physics.mdl"] = {12, "Suitcase"},
		["models/props_junk/wood_crate001a_damagedmax.mdl"] = {15, "Wooden Crate"},
		["models/props_junk/wood_crate001a_damaged.mdl"] = {15, "Wooden Crate"},
		["models/props_interiors/furniture_desk01a.mdl"] = {10, "Desk"},
		["models/props_c17/furnituredresser001a.mdl"] = {30, "Dresser"},
		["models/props_c17/furnituredrawer001a.mdl"] = {10, "Drawer"},
		["models/props_c17/furnituredrawer002a.mdl"] = {10, "Drawer"},
		["models/props_c17/furniturefridge001a.mdl"] = {15, "Fridge"},
		["models/props_c17/furnituredrawer003a.mdl"] = {12, "Drawer"},
		["models/weapons/w_suitcase_passenger.mdl"] = {12, "Suitcase"},
		["models/props_junk/trashdumpster01a.mdl"] = {20, "Dumpster"},
		["models/props_junk/wood_crate001a.mdl"] = {15, "Wooden Crate"},
		["models/props_junk/wood_crate002a.mdl"] = {15, "Wooden Crate"},
		["models/items/ammocrate_rockets.mdl"] = {20, "Ammo Crate"},
		["models/props_lab/filecabinet02.mdl"] = {15, "File Cabinet"},
		["models/items/ammocrate_grenade.mdl"] = {20, "Ammo Crate"},
		["models/props_junk/trashbin01a.mdl"] = {15, "Trash Bin"},
		["models/props_c17/suitcase001a.mdl"] = {12, "Suitcase"},
		["models/items/item_item_crate.mdl"] = {15, "Item Crate"},
		["models models/items/item_beacon_crate.mdl"] = {15, "Item Crate"},
		["models/props_c17/oildrum001.mdl"] = {14, "Oildrum"},
		["models/items/ammocrate_smg1.mdl"] = {20, "Ammo Crate"},
		["models/items/ammocrate_ar2.mdl"] = {20, "Ammo Crate"},
		["models/props_c17/cashregister01a.mdl"] = {3, "Cash Register"},
		["models/props_forest/footlocker01_closed.mdl"] = {25, "Footlocker"},
		["models/props/de_prodigy/ammo_can_02.mdl"] = {8, "Weapon Case"},
		["models/props_industrial/toolbox.mdl"] = {15, "Tool Cabinet"},
		["models/props_c17/lockers001a.mdl"] = {20, "Lockers"},
		["models/props_wasteland/kitchen_fridge001a.mdl"] = {20, "Refrigerator"},
		["models/props_c17/FurnitureWashingmachine001a.mdl"] = {5, "Washing Machine"},
		["models/props_interiors/Furniture_Vanity01a.mdl"] = {5, "Vanity Table"},
		["models/props_junk/cardboard_box001a.mdl"] = {10, "Cardboard Box"},
		["models/props_junk/cardboard_box001b.mdl"] = {10, "Cardboard Box"},
		["models/props_junk/cardboard_box002a.mdl"] = {10, "Cardboard Box"},
		["models/props_junk/cardboard_box002b.mdl"] = {10, "Cardboard Box"},
		["models/props_junk/cardboard_box003a.mdl"] = {10, "Cardboard Box"},
		["models/props_junk/cardboard_box003b.mdl"] = {10, "Cardboard Box"},
		["models/props_junk/cardboard_box004a.mdl"] = {1, "Cardboard Box"},
		["models/props_trainstation/trashcan_indoor001a.mdl"] = {7, "Trash Can"},
		["models/props_trainstation/trashcan_indoor001b.mdl"] = {7, "Trash Can"},
		["models/props_wasteland/kitchen_stove001a.mdl"] = {4, "Kitchen Stove"},
		["models/props_wasteland/kitchen_stove002a.mdl"] = {4, "Kitchen Stove"},
		["models/props_wasteland/laundry_dryer001.mdl"] = {10, "Laundry Machine"},
		["models/props_wasteland/laundry_dryer002.mdl"] = {10, "Laundry Machine"},
		["models/props_wasteland/laundry_washer001a.mdl"] = {5, "Washing Machine"},
		["models/props_wasteland/laundry_washer003.mdl"] = {10, "Washing Machine"},
		["models/props_c17/BriefCase001a.mdl"] = {2, "Briefcase"},
		["models/props_c17/SuitCase001a.mdl"] = {3, "Suitcase"},
		["models/props_c17/SuitCase_Passenger_Physics.mdl"] = {2, "Suitcase"},
		["models/props_junk/TrashBin01a.mdl"] = {3, "Trash Bin"}


	};
end;